--- makefile.orig	2010-05-12 00:37:53.000000000 +0300
+++ makefile	2010-05-12 01:58:14.000000000 +0300
@@ -101,12 +101,12 @@
   	LDFLAGS += -framework Cocoa -framework OpenGL -framework IOKit -framework CoreFoundation -framework Carbon -framework OpenAL
   	LDFLAGS += ./libSDL-1.2.0.dylib ./libSDLmain-osx.a
 else
-	CXX := /opt/crosstool/gcc-4.1.2-glibc-2.3.6/i686-unknown-linux-gnu/i686-unknown-linux-gnu/bin/g++
-	CC := /opt/crosstool/gcc-4.1.2-glibc-2.3.6/i686-unknown-linux-gnu/i686-unknown-linux-gnu/bin/gcc
-	LD := /opt/crosstool/gcc-4.1.2-glibc-2.3.6/i686-unknown-linux-gnu/i686-unknown-linux-gnu/bin/g++
+	CXX := g++
+	CC := gcc
+	LD := g++
 
   	CFLAGS += -DPLATFORM_LINUX=1
-  	LDFLAGS += ./libSDL-1.2.so.0 -Wl,-rpath,\$$ORIGIN
+  	LDFLAGS += -L/usr/lib -lSDL -lopenal
 
   	ifeq ($(strip $(use_devil)),true)
     	LDFLAGS += ./libIL.so.1 ./libILU.so.1 ./libILUT.so.1
@@ -115,7 +115,7 @@
   	ifeq ($(strip $(use_fmod)),true)
     	POSTLDFLAGS += -lpthread ./libfmod-linux-x86.a
   	else
-    	LDFLAGS += ./libopenal.so.1
+    	LDFLAGS += -L/usr/lib -lopenal
   	endif
 endif
 
